import Footer from '@/components/navigation/footer/Footer';
import Header from '@/components/navigation/header/Header';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="max-w-5xl flex flex-col md:flex-col mx-4 pt-20 lg:mx-auto min-h-screen font-mono text-sm">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
